CREATE SEQUENCE if not exists tickets_history_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE if not exists tickets_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE expert_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE sector_seq START WITH 1 INCREMENT BY 1;
